-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scheduled_trip_id uuid NOT NULL,
  bus_id uuid NOT NULL,
  permit_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  conductor_id uuid,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  current_speed_kmh numeric,
  heading numeric,
  current_stop_id uuid,
  next_stop_id uuid,
  stops_completed ARRAY,
  actual_departure_time timestamp with time zone,
  estimated_arrival_time timestamp with time zone,
  actual_arrival_time timestamp with time zone,
  status character varying NOT NULL DEFAULT 'not_started'::character varying CHECK (status::text = ANY (ARRAY['not_started'::character varying, 'in_transit'::character varying, 'at_stop'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  current_passenger_count integer DEFAULT 0,
  tracking_device_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT active_trips_pkey PRIMARY KEY (id),
  CONSTRAINT active_trips_scheduled_trip_id_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT active_trips_bus_id_fkey FOREIGN KEY (bus_id) REFERENCES public.buses(id),
  CONSTRAINT active_trips_permit_id_fkey FOREIGN KEY (permit_id) REFERENCES public.route_permits(id),
  CONSTRAINT active_trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.bus_staff(id),
  CONSTRAINT active_trips_conductor_id_fkey FOREIGN KEY (conductor_id) REFERENCES public.bus_staff(id),
  CONSTRAINT active_trips_current_stop_id_fkey FOREIGN KEY (current_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT active_trips_next_stop_id_fkey FOREIGN KEY (next_stop_id) REFERENCES public.master_route_stops(id)
);
CREATE TABLE public.admin_refresh_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_user_id uuid NOT NULL,
  token_hash character varying NOT NULL UNIQUE,
  device_id character varying,
  device_type character varying,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  CONSTRAINT admin_refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT admin_refresh_tokens_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  password_hash character varying NOT NULL,
  full_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  function_permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  role text NOT NULL DEFAULT 'admin'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'supervisor'::text, 'admin'::text])),
  app_scope text CHECK ((app_scope = ANY (ARRAY['bus'::text, 'driver'::text, 'lounges'::text, 'passenger'::text])) OR app_scope IS NULL),
  supervisor_id uuid,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_users(id),
  CONSTRAINT admin_users_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.advertisement_calculation (
  traffic_level text NOT NULL,
  cost_per_second numeric NOT NULL CHECK (cost_per_second >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT advertisement_calculation_pkey PRIMARY KEY (traffic_level)
);
CREATE TABLE public.advertisement_cost_aggregates (
  advertisement_id text NOT NULL,
  advertisement_name text NOT NULL,
  traffic_level text NOT NULL,
  cost_date date NOT NULL,
  play_count integer NOT NULL DEFAULT 0,
  total_seconds integer NOT NULL DEFAULT 0,
  total_cost numeric NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT advertisement_cost_aggregates_pkey PRIMARY KEY (advertisement_id, traffic_level, cost_date),
  CONSTRAINT fk_ad_cost_agg_traffic_level FOREIGN KEY (traffic_level) REFERENCES public.advertisement_calculation(traffic_level)
);
CREATE TABLE public.advertisement_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_name character varying NOT NULL UNIQUE,
  lounges text,
  no_of_advertisements integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT advertisement_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.advertisement_playback_logs (
  id bigint NOT NULL DEFAULT nextval('advertisement_playback_logs_id_seq'::regclass),
  advertisement_id text NOT NULL,
  advertisement_name text NOT NULL,
  traffic_level text NOT NULL,
  duration_seconds integer NOT NULL CHECK (duration_seconds > 0),
  played_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT advertisement_playback_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ad_calc_traffic_level FOREIGN KEY (traffic_level) REFERENCES public.advertisement_calculation(traffic_level)
);
CREATE TABLE public.advertisements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  advertisement_name character varying NOT NULL,
  description text,
  advertisement_category character varying CHECK (advertisement_category::text = ANY (ARRAY['internal branding'::character varying, 'commercial'::character varying, 'seasonal'::character varying, 'event'::character varying, 'emergency'::character varying]::text[])),
  media_duration integer,
  media_url text,
  media_type character varying CHECK (media_type::text = ANY (ARRAY['image'::character varying, 'video'::character varying, 'gif'::character varying, 'audio'::character varying, 'html'::character varying]::text[])),
  lounge_group_name character varying,
  priority character varying CHECK (priority::text = ANY (ARRAY['high'::character varying, 'medium'::character varying, 'low'::character varying]::text[])),
  version integer DEFAULT 1,
  schedule_type character varying CHECK (schedule_type::text = ANY (ARRAY['recurring'::character varying, 'one-time'::character varying, 'on startup'::character varying, 'on idle'::character varying]::text[])),
  frequency character varying CHECK (frequency::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])),
  recurrence_interval integer,
  occurs_once_at timestamp without time zone,
  occurs_every_interval integer,
  weekly_days character varying,
  monthly_day_of_month integer CHECK (monthly_day_of_month >= 1 AND monthly_day_of_month <= 31),
  monthly_week character varying CHECK (monthly_week::text = ANY (ARRAY['first'::character varying, 'second'::character varying, 'third'::character varying, 'fourth'::character varying, 'last'::character varying]::text[])),
  monthly_day character varying,
  start_time time without time zone,
  end_time time without time zone,
  max_idle_loop_duration integer,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'paused'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  start_date date,
  end_date date,
  CONSTRAINT advertisements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  ip_address character varying,
  user_agent text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.booking_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  intent_type character varying NOT NULL DEFAULT 'combined'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'held'::booking_intent_status,
  bus_intent jsonb,
  pre_trip_lounge_intent jsonb,
  post_trip_lounge_intent jsonb,
  bus_fare numeric DEFAULT 0,
  pre_lounge_fare numeric DEFAULT 0,
  post_lounge_fare numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency character varying DEFAULT 'LKR'::character varying,
  pricing_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  payment_reference character varying UNIQUE,
  payment_status USER-DEFINED,
  payment_gateway character varying DEFAULT 'payable'::character varying,
  bus_booking_id uuid,
  pre_lounge_booking_id uuid,
  post_lounge_booking_id uuid,
  expires_at timestamp with time zone NOT NULL,
  payment_initiated_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  expired_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  idempotency_key character varying UNIQUE,
  payment_uid character varying,
  payment_status_indicator character varying,
  passenger_name character varying,
  passenger_phone character varying,
  CONSTRAINT booking_intents_pkey PRIMARY KEY (id),
  CONSTRAINT booking_intents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_reference character varying NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  booking_type character varying NOT NULL CHECK (booking_type::text = ANY (ARRAY['bus_only'::character varying, 'lounge_only'::character varying, 'bus_with_lounge'::character varying]::text[])),
  bus_total numeric DEFAULT 0 CHECK (bus_total >= 0::numeric),
  lounge_total numeric DEFAULT 0 CHECK (lounge_total >= 0::numeric),
  pre_order_total numeric DEFAULT 0 CHECK (pre_order_total >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  promo_code character varying,
  promo_discount_type character varying,
  promo_discount_value numeric DEFAULT 0,
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'collect_on_bus'::character varying, 'free'::character varying, 'failed'::character varying, 'refunded'::character varying, 'partial_refund'::character varying]::text[])),
  payment_method character varying,
  payment_reference character varying,
  payment_gateway character varying,
  paid_at timestamp with time zone,
  booking_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (booking_status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'partial_cancel'::character varying]::text[])),
  passenger_name character varying NOT NULL,
  passenger_phone character varying NOT NULL,
  passenger_email character varying,
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by_user_id uuid,
  completed_at timestamp with time zone,
  refund_amount numeric DEFAULT 0 CHECK (refund_amount >= 0::numeric),
  refund_reference character varying,
  refunded_at timestamp with time zone,
  booking_source character varying DEFAULT 'app'::character varying CHECK (booking_source::text = ANY (ARRAY['app'::character varying, 'web'::character varying, 'agent'::character varying, 'kiosk'::character varying]::text[])),
  device_info jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.broadcast_messages (
  id uuid NOT NULL,
  message text NOT NULL,
  priority text NOT NULL DEFAULT 'normal'::text,
  display_duration_seconds integer NOT NULL CHECK (display_duration_seconds > 0),
  frequency_seconds integer NOT NULL CHECK (frequency_seconds > 0),
  start_at timestamp with time zone NOT NULL DEFAULT now(),
  end_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  show_on_lounge_tv boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT broadcast_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bus_booking_seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_booking_id uuid NOT NULL,
  scheduled_trip_id uuid NOT NULL,
  trip_seat_id uuid,
  passenger_name character varying NOT NULL,
  passenger_phone character varying,
  passenger_email character varying,
  passenger_gender character varying CHECK (passenger_gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying]::text[])),
  passenger_nic character varying,
  is_primary_passenger boolean DEFAULT false,
  status character varying DEFAULT 'booked'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'booked'::character varying, 'checked_in'::character varying, 'boarded'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_booking_seats_pkey PRIMARY KEY (id),
  CONSTRAINT bus_booking_seats_booking_fkey FOREIGN KEY (bus_booking_id) REFERENCES public.bus_bookings(id),
  CONSTRAINT bus_booking_seats_trip_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT bus_booking_seats_trip_seat_fkey FOREIGN KEY (trip_seat_id) REFERENCES public.trip_seats(id)
);
CREATE TABLE public.bus_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL,
  scheduled_trip_id uuid NOT NULL,
  boarding_stop_id uuid,
  alighting_stop_id uuid,
  number_of_seats integer NOT NULL CHECK (number_of_seats > 0),
  fare_per_seat numeric NOT NULL CHECK (fare_per_seat >= 0::numeric),
  total_fare numeric NOT NULL CHECK (total_fare >= 0::numeric),
  status character varying NOT NULL DEFAULT 'confirmed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'checked_in'::character varying, 'boarded'::character varying, 'in_transit'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  checked_in_at timestamp with time zone,
  checked_in_by_user_id uuid,
  boarded_at timestamp with time zone,
  boarded_by_user_id uuid,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  qr_code_data character varying UNIQUE,
  qr_generated_at timestamp with time zone,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bus_bookings_booking_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT bus_bookings_trip_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT bus_bookings_boarding_fkey FOREIGN KEY (boarding_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT bus_bookings_alighting_fkey FOREIGN KEY (alighting_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT bus_bookings_checkin_staff_fkey FOREIGN KEY (checked_in_by_user_id) REFERENCES public.users(id),
  CONSTRAINT bus_bookings_boarding_staff_fkey FOREIGN KEY (boarded_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bus_owner_routes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  master_route_id uuid NOT NULL,
  custom_route_name character varying NOT NULL,
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['UP'::character varying, 'DOWN'::character varying]::text[])),
  selected_stop_ids ARRAY NOT NULL CHECK (array_length(selected_stop_ids, 1) >= 2),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_owner_routes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_bus_owner_routes_master_route FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id),
  CONSTRAINT fk_bus_owner_routes_bus_owner FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id)
);
CREATE TABLE public.bus_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  company_name character varying,
  license_number character varying UNIQUE,
  contact_person character varying,
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  business_email character varying,
  business_phone character varying,
  tax_id character varying,
  bank_account_details jsonb,
  total_buses integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  identity_or_incorporation_no character varying,
  CONSTRAINT bus_owners_pkey PRIMARY KEY (id),
  CONSTRAINT bus_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bus_seat_layout_seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id uuid NOT NULL,
  row_number integer NOT NULL CHECK (row_number > 0),
  row_label character varying NOT NULL,
  position integer NOT NULL CHECK ("position" >= 1 AND "position" <= 6),
  seat_number character varying NOT NULL,
  is_window_seat boolean DEFAULT false,
  is_aisle_seat boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_seat_layout_seats_pkey PRIMARY KEY (id),
  CONSTRAINT bus_seat_layout_seats_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.bus_seat_layout_templates(id)
);
CREATE TABLE public.bus_seat_layout_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_name character varying NOT NULL,
  total_rows integer NOT NULL CHECK (total_rows > 0 AND total_rows <= 20),
  total_seats integer NOT NULL DEFAULT 0 CHECK (total_seats >= 0),
  description text,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_seat_layout_templates_pkey PRIMARY KEY (id),
  CONSTRAINT bus_seat_layout_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.bus_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  staff_type USER-DEFINED NOT NULL,
  license_number character varying,
  license_expiry_date date,
  experience_years integer DEFAULT 0,
  emergency_contact character varying,
  emergency_contact_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  first_name character varying,
  last_name character varying,
  is_verified boolean DEFAULT false,
  verification_status USER-DEFINED DEFAULT 'pending'::staff_verification_status,
  CONSTRAINT bus_staff_pkey PRIMARY KEY (id),
  CONSTRAINT bus_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT bus_staff_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.bus_staff_employment (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  staff_id uuid NOT NULL,
  bus_owner_id uuid NOT NULL,
  employment_status character varying NOT NULL DEFAULT 'active'::character varying CHECK (employment_status::text = ANY (ARRAY['pending'::character varying, 'active'::character varying, 'inactive'::character varying, 'terminated'::character varying, 'resigned'::character varying, 'suspended'::character varying]::text[])),
  hire_date date NOT NULL DEFAULT CURRENT_DATE,
  termination_date date,
  termination_reason text,
  salary_amount numeric CHECK (salary_amount IS NULL OR salary_amount >= 0::numeric),
  performance_rating numeric DEFAULT 5.00 CHECK (performance_rating >= 0.00 AND performance_rating <= 5.00),
  total_trips_completed integer DEFAULT 0,
  is_current boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_staff_employment_pkey PRIMARY KEY (id),
  CONSTRAINT bus_staff_employment_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.bus_staff(id),
  CONSTRAINT bus_staff_employment_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id)
);
CREATE TABLE public.buses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  permit_id uuid NOT NULL,
  bus_number character varying NOT NULL,
  license_plate character varying NOT NULL UNIQUE,
  bus_type character varying NOT NULL,
  manufacturing_year integer CHECK (manufacturing_year >= 1900 AND manufacturing_year::numeric <= (EXTRACT(year FROM CURRENT_DATE) + 1::numeric)),
  last_maintenance_date date,
  insurance_expiry date,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'maintenance'::character varying, 'inactive'::character varying]::text[])),
  has_wifi boolean NOT NULL DEFAULT false,
  has_ac boolean NOT NULL DEFAULT false,
  has_charging_ports boolean NOT NULL DEFAULT false,
  has_entertainment boolean NOT NULL DEFAULT false,
  has_refreshments boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  seat_layout_id uuid,
  CONSTRAINT buses_pkey PRIMARY KEY (id),
  CONSTRAINT fk_bus_owner FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT fk_permit FOREIGN KEY (permit_id) REFERENCES public.route_permits(id),
  CONSTRAINT fk_buses_seat_layout FOREIGN KEY (seat_layout_id) REFERENCES public.bus_seat_layout_templates(id)
);
CREATE TABLE public.complaint_escalation_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  complaint_id uuid NOT NULL,
  level integer NOT NULL,
  team_name character varying NOT NULL,
  escalated_at timestamp without time zone NOT NULL DEFAULT now(),
  escalated_by character varying NOT NULL,
  reason text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  from_admin_id uuid,
  to_admin_id uuid,
  CONSTRAINT complaint_escalation_history_pkey PRIMARY KEY (id),
  CONSTRAINT complaint_escalation_history_complaint_id_fkey FOREIGN KEY (complaint_id) REFERENCES public.report_issues(id),
  CONSTRAINT complaint_escalation_history_from_admin_id_fkey FOREIGN KEY (from_admin_id) REFERENCES public.admin_users(id),
  CONSTRAINT complaint_escalation_history_to_admin_id_fkey FOREIGN KEY (to_admin_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.complaint_escalations (
  complaint_id uuid NOT NULL,
  current_level integer NOT NULL DEFAULT 1,
  current_team character varying NOT NULL,
  assigned_to_admin_id uuid,
  last_escalated_at timestamp without time zone NOT NULL DEFAULT now(),
  next_escalation_due timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  source_app text CHECK (source_app = ANY (ARRAY['bus'::text, 'driver'::text, 'lounges'::text, 'passenger'::text])),
  previous_assigned_admin_id uuid,
  CONSTRAINT complaint_escalations_pkey PRIMARY KEY (complaint_id),
  CONSTRAINT complaint_escalations_complaint_id_fkey FOREIGN KEY (complaint_id) REFERENCES public.report_issues(id),
  CONSTRAINT complaint_escalations_assigned_to_admin_id_fkey FOREIGN KEY (assigned_to_admin_id) REFERENCES public.admin_users(id),
  CONSTRAINT complaint_escalations_previous_assigned_admin_id_fkey FOREIGN KEY (previous_assigned_admin_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.current_locations (
  trip_id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  route_name character varying NOT NULL,
  current_point_index integer NOT NULL DEFAULT 0,
  current_latitude numeric NOT NULL,
  current_longitude numeric NOT NULL,
  total_points integer NOT NULL,
  speed_multiplier integer NOT NULL DEFAULT 1,
  is_animating boolean NOT NULL DEFAULT false,
  progress_percentage numeric NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT current_locations_pkey PRIMARY KEY (trip_id),
  CONSTRAINT current_locations_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.master_routes(id)
);
CREATE TABLE public.lounge_ads (
  id uuid NOT NULL,
  lounge_id uuid,
  advertisement_name text NOT NULL,
  media_url text NOT NULL,
  media_type text NOT NULL,
  duration_seconds integer NOT NULL CHECK (duration_seconds > 0),
  priority text NOT NULL DEFAULT 'normal'::text,
  is_active boolean NOT NULL DEFAULT true,
  is_default_for_all boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lounge_ads_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_ads_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id)
);
CREATE TABLE public.lounge_booking_driver_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lounge_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  lounge_booking_id uuid NOT NULL,
  guest_name character varying NOT NULL,
  guest_contact character varying NOT NULL,
  driver_contact character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT lounge_booking_driver_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_booking_driver_assignments_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_booking_driver_assignments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.lounge_drivers(id),
  CONSTRAINT lounge_booking_driver_assignments_lounge_booking_id_fkey FOREIGN KEY (lounge_booking_id) REFERENCES public.lounge_bookings(id),
  CONSTRAINT fk_lounge FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT fk_driver FOREIGN KEY (driver_id) REFERENCES public.lounge_drivers(id),
  CONSTRAINT fk_booking FOREIGN KEY (lounge_booking_id) REFERENCES public.lounge_bookings(id)
);
CREATE TABLE public.lounge_booking_guests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_booking_id uuid NOT NULL,
  guest_name character varying NOT NULL,
  guest_phone character varying,
  guest_nic character varying,
  is_primary_guest boolean DEFAULT false,
  checked_in boolean DEFAULT false,
  checked_in_at timestamp with time zone,
  checked_out boolean DEFAULT false,
  checked_out_at timestamp with time zone,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_booking_guests_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_booking_guests_booking_fkey FOREIGN KEY (lounge_booking_id) REFERENCES public.lounge_bookings(id)
);
CREATE TABLE public.lounge_booking_pre_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_booking_id uuid NOT NULL,
  product_id uuid,
  product_name character varying NOT NULL,
  product_type character varying,
  product_image_url text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric CHECK (unit_price >= 0::numeric),
  total_price numeric CHECK (total_price >= 0::numeric),
  delivery_time timestamp with time zone,
  status USER-DEFINED DEFAULT 'pending'::lounge_booking_pre_order_status CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'confirmed'::character varying::text, 'preparing'::character varying::text, 'ready'::character varying::text, 'delivered'::character varying::text, 'cancelled'::character varying::text])),
  prepared_at timestamp with time zone,
  prepared_by_user_id uuid,
  delivered_at timestamp with time zone,
  delivered_by_user_id uuid,
  notes text,
  staff_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  delivery_preference USER-DEFINED NOT NULL DEFAULT 'on_check_in'::lounge_booking_delivery_preference,
  CONSTRAINT lounge_booking_pre_orders_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_booking_pre_orders_product_fkey FOREIGN KEY (product_id) REFERENCES public.lounge_products(id),
  CONSTRAINT lounge_booking_pre_orders_prepared_by_fkey FOREIGN KEY (prepared_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_booking_pre_orders_delivered_by_fkey FOREIGN KEY (delivered_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_booking_pre_orders_booking_fkey FOREIGN KEY (lounge_booking_id) REFERENCES public.lounge_bookings(id)
);
CREATE TABLE public.lounge_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  master_booking_id uuid,
  lounge_id uuid,
  booking_type text NOT NULL,
  bus_booking_id uuid,
  lounge_name character varying NOT NULL DEFAULT 'Unknown Lounge'::character varying,
  lounge_address text,
  lounge_phone character varying,
  scheduled_arrival timestamp with time zone NOT NULL,
  scheduled_departure timestamp with time zone,
  custom_duration_minutes integer,
  bus_departure_time timestamp with time zone,
  bus_arrival_time timestamp with time zone,
  number_of_guests integer NOT NULL DEFAULT 1 CHECK (number_of_guests > 0),
  price_per_guest numeric DEFAULT 0 CHECK (price_per_guest >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  pre_order_total numeric DEFAULT 0 CHECK (pre_order_total >= 0::numeric),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::lounge_booking_status CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'confirmed'::character varying::text, 'checked_in'::character varying::text, 'in_lounge'::character varying::text, 'checked_out'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text, 'no_show'::character varying::text])),
  actual_arrival timestamp with time zone,
  actual_departure timestamp with time zone,
  checked_in_by_user_id uuid,
  checked_out_by_user_id uuid,
  qr_code_data character varying,
  qr_generated_at timestamp with time zone,
  assigned_table character varying,
  assigned_zone character varying,
  selected_amenities jsonb DEFAULT '[]'::jsonb,
  special_requests text,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by_user_id uuid,
  reminder_sent_at timestamp with time zone,
  bus_departure_alert_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_reference character varying UNIQUE,
  user_id uuid,
  base_price numeric DEFAULT 0 CHECK (base_price >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'partial'::character varying, 'collect_on_site'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  primary_guest_name character varying DEFAULT 'Guest'::character varying,
  primary_guest_phone character varying DEFAULT ''::character varying,
  promo_code character varying,
  internal_notes text,
  pricing_type text NOT NULL,
  CONSTRAINT lounge_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_bookings_lounge_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_bookings_bus_fkey FOREIGN KEY (bus_booking_id) REFERENCES public.bus_bookings(id),
  CONSTRAINT lounge_bookings_checkin_staff_fkey FOREIGN KEY (checked_in_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_bookings_checkout_staff_fkey FOREIGN KEY (checked_out_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_capacity_holds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lounge_id uuid NOT NULL,
  intent_id uuid NOT NULL,
  date date NOT NULL,
  time_slot_start time without time zone NOT NULL,
  time_slot_end time without time zone NOT NULL,
  guests_count integer NOT NULL DEFAULT 1 CHECK (guests_count > 0),
  held_until timestamp with time zone NOT NULL,
  status character varying DEFAULT 'held'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_capacity_holds_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_capacity_holds_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_capacity_holds_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES public.booking_intents(id)
);
CREATE TABLE public.lounge_drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lounge_id uuid NOT NULL,
  name character varying NOT NULL,
  nic_number character varying NOT NULL,
  contact_no character varying NOT NULL,
  vehicle_no character varying NOT NULL,
  vehicle_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::lounge_driver_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lounge_drivers_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_drivers_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id)
);
CREATE TABLE public.lounge_marketplace_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  icon_name character varying,
  icon_url text,
  parent_category_id uuid,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_marketplace_categories_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_marketplace_categories_parent_fkey FOREIGN KEY (parent_category_id) REFERENCES public.lounge_marketplace_categories(id)
);
CREATE TABLE public.lounge_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_name character varying NOT NULL,
  product_type character varying NOT NULL,
  product_image_url text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  total_price numeric NOT NULL CHECK (total_price >= 0::numeric),
  item_status USER-DEFINED DEFAULT 'pending'::lounge_order_item_status CHECK (item_status::text = ANY (ARRAY['pending'::character varying::text, 'confirmed'::character varying::text, 'preparing'::character varying::text, 'ready'::character varying::text, 'delivered'::character varying::text, 'cancelled'::character varying::text])),
  notes text,
  modifiers jsonb DEFAULT '[]'::jsonb,
  started_preparing_at timestamp with time zone,
  ready_at timestamp with time zone,
  delivered_at timestamp with time zone,
  prepared_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_order_items_order_fkey FOREIGN KEY (order_id) REFERENCES public.lounge_orders(id),
  CONSTRAINT lounge_order_items_product_fkey FOREIGN KEY (product_id) REFERENCES public.lounge_products(id),
  CONSTRAINT lounge_order_items_prepared_by_fkey FOREIGN KEY (prepared_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_reference character varying NOT NULL,
  lounge_id uuid NOT NULL,
  user_id uuid,
  lounge_booking_id uuid,
  order_type character varying DEFAULT 'in_lounge'::character varying CHECK (order_type::text = ANY (ARRAY['in_lounge'::character varying, 'table_service'::character varying, 'takeaway'::character varying, 'walk_in'::character varying]::text[])),
  table_number character varying,
  zone character varying,
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  service_charge numeric DEFAULT 0 CHECK (service_charge >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  promotion_id uuid,
  promo_code character varying,
  order_status USER-DEFINED NOT NULL DEFAULT 'pending'::lounge_order_status CHECK (order_status::text = ANY (ARRAY['pending'::character varying::text, 'confirmed'::character varying::text, 'preparing'::character varying::text, 'ready'::character varying::text, 'served'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending'::lounge_order_payment_status CHECK (payment_status::text = ANY (ARRAY['pending'::character varying::text, 'paid'::character varying::text, 'failed'::character varying::text, 'refunded'::character varying::text, 'add_to_bill'::character varying::text])),
  payment_method character varying,
  payment_reference character varying,
  paid_at timestamp with time zone,
  taken_by_user_id uuid,
  served_by_user_id uuid,
  confirmed_at timestamp with time zone,
  preparing_at timestamp with time zone,
  ready_at timestamp with time zone,
  served_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  cancelled_by_user_id uuid,
  customer_name character varying,
  customer_phone character varying,
  special_instructions text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_orders_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_orders_cancelled_by_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_orders_lounge_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_orders_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_orders_booking_fkey FOREIGN KEY (lounge_booking_id) REFERENCES public.lounge_bookings(id),
  CONSTRAINT lounge_orders_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES public.lounge_promotions(id),
  CONSTRAINT lounge_orders_taken_by_fkey FOREIGN KEY (taken_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_orders_served_by_fkey FOREIGN KEY (served_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  business_name character varying,
  business_license character varying,
  manager_full_name character varying,
  manager_nic_number character varying,
  manager_email character varying,
  registration_step USER-DEFINED DEFAULT 'phone_verified'::lounge_owner_registration_step,
  profile_completed boolean DEFAULT false,
  verification_status USER-DEFINED DEFAULT 'pending'::lounge_owner_verification_status,
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  contact_number text,
  nic text,
  district character varying,
  CONSTRAINT lounge_owners_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_owners_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_product_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid,
  order_item_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text,
  images ARRAY,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  not_helpful_count integer DEFAULT 0,
  owner_response text,
  owner_response_at timestamp with time zone,
  owner_response_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_product_reviews_product_fkey FOREIGN KEY (product_id) REFERENCES public.lounge_products(id),
  CONSTRAINT lounge_product_reviews_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_product_reviews_order_fkey FOREIGN KEY (order_id) REFERENCES public.lounge_orders(id),
  CONSTRAINT lounge_product_reviews_order_item_fkey FOREIGN KEY (order_item_id) REFERENCES public.lounge_order_items(id),
  CONSTRAINT lounge_product_reviews_owner_response_fkey FOREIGN KEY (owner_response_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  product_type USER-DEFINED NOT NULL DEFAULT 'product'::lounge_product_type CHECK (product_type::text = ANY (ARRAY['product'::character varying::text, 'service'::character varying::text, 'combo'::character varying::text])),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  discounted_price numeric CHECK (discounted_price IS NULL OR discounted_price >= 0::numeric),
  image_url text,
  thumbnail_url text,
  stock_status USER-DEFINED DEFAULT 'in_stock'::lounge_product_stock_status CHECK (stock_status::text = ANY (ARRAY['in_stock'::character varying::text, 'low_stock'::character varying::text, 'out_of_stock'::character varying::text, 'made_to_order'::character varying::text])),
  stock_quantity integer,
  is_available boolean DEFAULT true,
  is_pre_orderable boolean DEFAULT false,
  available_from time without time zone,
  available_until time without time zone,
  available_days ARRAY DEFAULT ARRAY['mon'::text, 'tue'::text, 'wed'::text, 'thu'::text, 'fri'::text, 'sat'::text, 'sun'::text],
  service_duration_minutes integer,
  is_vegetarian boolean DEFAULT false,
  is_vegan boolean DEFAULT false,
  is_halal boolean DEFAULT false,
  allergens ARRAY,
  calories integer,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  tags ARRAY,
  average_rating numeric DEFAULT 0.0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price_rate_type USER-DEFINED,
  CONSTRAINT lounge_products_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_products_lounge_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_products_category_fkey FOREIGN KEY (category_id) REFERENCES public.lounge_marketplace_categories(id)
);
CREATE TABLE public.lounge_promotions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_id uuid NOT NULL,
  promo_code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed_amount'::character varying, 'free_item'::character varying]::text[])),
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  min_order_amount numeric,
  max_discount_amount numeric,
  applies_to character varying DEFAULT 'all'::character varying CHECK (applies_to::text = ANY (ARRAY['all'::character varying, 'lounge_booking'::character varying, 'products'::character varying, 'services'::character varying, 'specific_products'::character varying]::text[])),
  applicable_product_ids ARRAY,
  applicable_category_ids ARRAY,
  valid_from timestamp with time zone NOT NULL,
  valid_until timestamp with time zone NOT NULL,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  usage_limit_per_user integer DEFAULT 1,
  first_time_users_only boolean DEFAULT false,
  min_loyalty_points integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_promotions_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_promotions_lounge_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id)
);
CREATE TABLE public.lounge_routes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_id uuid NOT NULL,
  master_route_id uuid NOT NULL,
  stop_before_id uuid NOT NULL,
  stop_after_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lounge_routes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_lounge_routes_stop_after FOREIGN KEY (stop_after_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT fk_lounge_routes_lounge FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT fk_lounge_routes_master_route FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id),
  CONSTRAINT fk_lounge_routes_stop_before FOREIGN KEY (stop_before_id) REFERENCES public.master_route_stops(id)
);
CREATE TABLE public.lounge_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_id uuid NOT NULL,
  user_id uuid,
  full_name character varying,
  nic_number character varying,
  email character varying,
  employment_status USER-DEFINED DEFAULT 'active'::lounge_staff_employment_status CHECK (employment_status::text = ANY (ARRAY['active'::character varying::text, 'terminated'::character varying::text, 'suspended'::character varying::text])),
  hired_date date,
  terminated_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  approval_status USER-DEFINED NOT NULL DEFAULT 'pending'::lounge_staff_approval_status,
  CONSTRAINT lounge_staff_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_staff_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_transport_location_prices (
  lounge_id uuid NOT NULL,
  location_id uuid NOT NULL,
  three_wheeler_price numeric NOT NULL DEFAULT 0 CHECK (three_wheeler_price >= 0::numeric),
  car_price numeric NOT NULL DEFAULT 0 CHECK (car_price >= 0::numeric),
  van_price numeric NOT NULL DEFAULT 0 CHECK (van_price >= 0::numeric),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lounge_transport_location_prices_pkey PRIMARY KEY (lounge_id, location_id),
  CONSTRAINT lounge_transport_prices_lounge_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_transport_prices_location_fkey FOREIGN KEY (location_id) REFERENCES public.lounge_transport_locations(id)
);
CREATE TABLE public.lounge_transport_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lounge_id uuid NOT NULL,
  location character varying NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::lounge_location_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  est_duration integer CHECK (est_duration > 0),
  distance double precision CHECK (distance > 0::double precision),
  CONSTRAINT lounge_transport_locations_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_transport_locations_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id)
);
CREATE TABLE public.lounges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_owner_id uuid NOT NULL,
  lounge_name character varying NOT NULL,
  description text,
  address text NOT NULL,
  state character varying DEFAULT 'Western'::character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  contact_phone character varying,
  price_1_hour numeric DEFAULT NULL::numeric CHECK (price_1_hour IS NULL OR price_1_hour >= 0::numeric),
  price_2_hours numeric DEFAULT NULL::numeric CHECK (price_2_hours IS NULL OR price_2_hours >= 0::numeric),
  price_until_bus numeric DEFAULT NULL::numeric CHECK (price_until_bus IS NULL OR price_until_bus >= 0::numeric),
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  status USER-DEFINED DEFAULT 'pending'::lounge_status,
  is_operational boolean DEFAULT true,
  average_rating numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  capacity integer CHECK (capacity > 0),
  price_3_hours numeric CHECK (price_3_hours >= 0::numeric),
  owner_id uuid,
  marketplace_category_id uuid,
  verification_note text,
  total_staff integer NOT NULL DEFAULT 0,
  CONSTRAINT lounges_pkey PRIMARY KEY (id),
  CONSTRAINT lounges_lounge_owner_id_fkey FOREIGN KEY (lounge_owner_id) REFERENCES public.lounge_owners(id),
  CONSTRAINT lounges_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.lounge_owners(id),
  CONSTRAINT lounges_marketplace_category_id_fkey FOREIGN KEY (marketplace_category_id) REFERENCES public.lounge_marketplace_categories(id)
);
CREATE TABLE public.manual_booking_seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  manual_booking_id uuid NOT NULL,
  trip_seat_id uuid NOT NULL UNIQUE,
  seat_number character varying NOT NULL,
  seat_price numeric NOT NULL CHECK (seat_price >= 0::numeric),
  passenger_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT manual_booking_seats_pkey PRIMARY KEY (id),
  CONSTRAINT manual_booking_seats_booking_fkey FOREIGN KEY (manual_booking_id) REFERENCES public.manual_seat_bookings(id),
  CONSTRAINT manual_booking_seats_trip_seat_fkey FOREIGN KEY (trip_seat_id) REFERENCES public.trip_seats(id)
);
CREATE TABLE public.manual_seat_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_reference character varying NOT NULL UNIQUE,
  scheduled_trip_id uuid NOT NULL,
  created_by_user_id uuid NOT NULL,
  booking_type character varying NOT NULL CHECK (booking_type::text = ANY (ARRAY['phone'::character varying, 'agent'::character varying, 'walk_in'::character varying]::text[])),
  passenger_name character varying NOT NULL,
  passenger_phone character varying,
  passenger_nic character varying,
  passenger_notes text,
  boarding_stop_id uuid NOT NULL,
  alighting_stop_id uuid NOT NULL,
  departure_datetime timestamp with time zone NOT NULL,
  number_of_seats integer NOT NULL CHECK (number_of_seats > 0),
  total_fare numeric NOT NULL CHECK (total_fare >= 0::numeric),
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'collect_on_bus'::character varying, 'free'::character varying]::text[])),
  amount_paid numeric DEFAULT 0 CHECK (amount_paid >= 0::numeric),
  payment_method character varying,
  payment_notes text,
  status character varying NOT NULL DEFAULT 'confirmed'::character varying CHECK (status::text = ANY (ARRAY['confirmed'::character varying, 'checked_in'::character varying, 'boarded'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  confirmed_at timestamp with time zone DEFAULT now(),
  checked_in_at timestamp with time zone,
  boarded_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT manual_seat_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT manual_seat_bookings_boarding_fkey FOREIGN KEY (boarding_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT manual_seat_bookings_alighting_fkey FOREIGN KEY (alighting_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT manual_seat_bookings_trip_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT manual_seat_bookings_creator_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.master_route_stops (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  master_route_id uuid NOT NULL,
  stop_name character varying NOT NULL,
  stop_order integer NOT NULL,
  latitude numeric,
  longitude numeric,
  arrival_time_offset_minutes integer,
  is_major_stop boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_route_stops_pkey PRIMARY KEY (id),
  CONSTRAINT master_route_stops_master_route_id_fkey FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id)
);
CREATE TABLE public.master_routes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  route_number character varying NOT NULL UNIQUE,
  route_name character varying NOT NULL,
  origin_city character varying NOT NULL,
  destination_city character varying NOT NULL,
  total_distance_km numeric,
  estimated_duration_minutes integer,
  encoded_polyline text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_rate_limits (
  id integer NOT NULL DEFAULT nextval('otp_rate_limits_id_seq'::regclass),
  identifier character varying NOT NULL,
  identifier_type character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_verifications (
  id integer NOT NULL DEFAULT nextval('otp_verifications_id_seq'::regclass),
  phone character varying NOT NULL,
  otp_code character varying NOT NULL,
  purpose character varying DEFAULT 'login'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  ip_address character varying,
  user_agent text,
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.passengers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  first_name character varying,
  last_name character varying,
  email character varying,
  date_of_birth date,
  nic character varying,
  address text,
  city character varying,
  postal_code character varying,
  profile_photo_url text,
  profile_completed boolean NOT NULL DEFAULT false,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  preferred_seat_type character varying,
  special_requirements text,
  total_trips integer NOT NULL DEFAULT 0,
  loyalty_points integer NOT NULL DEFAULT 0,
  verification_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (verification_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])),
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT passengers_pkey PRIMARY KEY (id),
  CONSTRAINT passengers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT passengers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_audits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  intent_id uuid,
  payment_uid character varying,
  payment_reference character varying,
  event_type USER-DEFINED NOT NULL,
  event_source USER-DEFINED NOT NULL,
  expected_amount numeric,
  received_amount numeric,
  currency character varying DEFAULT 'LKR'::character varying,
  amounts_match boolean,
  payment_status character varying,
  gateway_transaction_id character varying,
  request_payload jsonb,
  response_payload jsonb,
  raw_body text,
  http_status_code integer,
  http_method character varying,
  endpoint_url text,
  error_message text,
  error_code character varying,
  processing_time_ms integer,
  is_duplicate boolean DEFAULT false,
  idempotency_key character varying,
  ip_address character varying,
  user_agent text,
  correlation_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT payment_audits_pkey PRIMARY KEY (id),
  CONSTRAINT payment_audits_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES public.booking_intents(id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash character varying NOT NULL UNIQUE,
  device_id character varying,
  device_type USER-DEFINED,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.report_issues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scheduled_trip_id uuid,
  active_trip_id uuid,
  reported_by_id uuid NOT NULL,
  issue_type character varying NOT NULL CHECK (issue_type::text = ANY (ARRAY['bus_delay'::character varying, 'maintenance_issue'::character varying, 'flat_wheel'::character varying, 'passenger_complaint'::character varying, 'safety_concern'::character varying, 'equipment_malfunction'::character varying, 'other'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'emergency'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'reported'::character varying CHECK (status::text = ANY (ARRAY['reported'::character varying, 'acknowledged'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  description text NOT NULL,
  latitude double precision,
  longitude double precision,
  location_address text,
  image_url text,
  resolved_at timestamp without time zone,
  resolved_by_id uuid,
  resolution_notes text,
  notified_passengers boolean DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_issues_pkey PRIMARY KEY (id),
  CONSTRAINT report_issues_scheduled_trip_id_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT report_issues_active_trip_id_fkey FOREIGN KEY (active_trip_id) REFERENCES public.active_trips(id),
  CONSTRAINT report_issues_reported_by_id_fkey FOREIGN KEY (reported_by_id) REFERENCES public.users(id),
  CONSTRAINT report_issues_resolved_by_id_fkey FOREIGN KEY (resolved_by_id) REFERENCES public.users(id)
);
CREATE TABLE public.road_report_votes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  report_id uuid NOT NULL,
  user_id uuid NOT NULL,
  vote_type character varying NOT NULL CHECK (vote_type::text = ANY (ARRAY['upvote'::character varying, 'downvote'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT road_report_votes_pkey PRIMARY KEY (id),
  CONSTRAINT road_report_votes_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.road_reports(id),
  CONSTRAINT road_report_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.road_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  report_type character varying NOT NULL CHECK (report_type::text = ANY (ARRAY['crash'::character varying, 'speed_trap'::character varying, 'slowdown'::character varying, 'construction'::character varying, 'lane_closure'::character varying, 'stalled_vehicle'::character varying, 'object_on_road'::character varying]::text[])),
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  location_description text,
  reported_by uuid,
  active_trip_id uuid,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'resolved'::character varying, 'expired'::character varying]::text[])),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '02:00:00'::interval),
  upvote_count integer DEFAULT 0 CHECK (upvote_count >= 0),
  downvote_count integer DEFAULT 0 CHECK (downvote_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT road_reports_pkey PRIMARY KEY (id),
  CONSTRAINT road_reports_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT road_reports_active_trip_id_fkey FOREIGN KEY (active_trip_id) REFERENCES public.active_trips(id)
);
CREATE TABLE public.route_permits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  permit_number character varying NOT NULL,
  bus_registration_number character varying NOT NULL,
  via ARRAY,
  approved_fare numeric NOT NULL CHECK (approved_fare > 0::numeric),
  issue_date date NOT NULL,
  expiry_date date NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  master_route_id uuid NOT NULL,
  permit_type character varying DEFAULT 'regular'::character varying,
  max_trips_per_day integer,
  allowed_bus_types ARRAY,
  restrictions text,
  verified_at timestamp with time zone,
  permit_document_url text,
  approved_seating_capacity integer CHECK (approved_seating_capacity IS NULL OR approved_seating_capacity > 0),
  CONSTRAINT route_permits_pkey PRIMARY KEY (id),
  CONSTRAINT route_permits_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT route_permits_master_route_id_fkey FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id)
);
CREATE TABLE public.scheduled_trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_schedule_id uuid,
  permit_id uuid,
  assigned_driver_id uuid,
  assigned_conductor_id uuid,
  is_bookable boolean DEFAULT false,
  base_fare numeric,
  status character varying NOT NULL DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assignment_deadline timestamp with time zone,
  bus_owner_route_id uuid,
  departure_datetime timestamp without time zone NOT NULL,
  estimated_duration_minutes integer NOT NULL,
  ever_published boolean NOT NULL DEFAULT false,
  seat_layout_id uuid,
  CONSTRAINT scheduled_trips_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_trips_trip_schedule_id_fkey FOREIGN KEY (trip_schedule_id) REFERENCES public.trip_schedules(id),
  CONSTRAINT scheduled_trips_permit_id_fkey FOREIGN KEY (permit_id) REFERENCES public.route_permits(id),
  CONSTRAINT scheduled_trips_assigned_driver_id_fkey FOREIGN KEY (assigned_driver_id) REFERENCES public.bus_staff(id),
  CONSTRAINT scheduled_trips_assigned_conductor_id_fkey FOREIGN KEY (assigned_conductor_id) REFERENCES public.bus_staff(id),
  CONSTRAINT fk_scheduled_trips_bus_owner_route FOREIGN KEY (bus_owner_route_id) REFERENCES public.bus_owner_routes(id),
  CONSTRAINT fk_scheduled_trips_seat_layout FOREIGN KEY (seat_layout_id) REFERENCES public.bus_seat_layout_templates(id)
);
CREATE TABLE public.search_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  from_input text,
  to_input text,
  from_stop_id uuid,
  to_stop_id uuid,
  results_count integer DEFAULT 0,
  response_time_ms integer,
  user_id uuid,
  ip_address character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT search_logs_pkey PRIMARY KEY (id),
  CONSTRAINT search_logs_from_stop_id_fkey FOREIGN KEY (from_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT search_logs_to_stop_id_fkey FOREIGN KEY (to_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT search_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trip_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  schedule_name character varying,
  recurrence_type character varying NOT NULL CHECK (recurrence_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'interval'::character varying]::text[])),
  departure_time time without time zone NOT NULL,
  base_fare numeric NOT NULL CHECK (base_fare > 0::numeric),
  is_active boolean DEFAULT true,
  valid_from date,
  valid_until date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  recurrence_interval integer CHECK (recurrence_interval IS NULL OR recurrence_interval > 0),
  bus_owner_route_id uuid,
  recurrence_days text,
  specific_dates text,
  estimated_duration_minutes integer,
  CONSTRAINT trip_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT trip_schedules_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT fk_trip_schedules_bus_owner_route FOREIGN KEY (bus_owner_route_id) REFERENCES public.bus_owner_routes(id)
);
CREATE TABLE public.trip_seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scheduled_trip_id uuid NOT NULL,
  seat_number character varying NOT NULL,
  seat_type character varying DEFAULT 'standard'::character varying CHECK (seat_type::text = ANY (ARRAY['standard'::character varying, 'window'::character varying, 'aisle'::character varying, 'premium'::character varying, 'accessible'::character varying]::text[])),
  row_number integer NOT NULL,
  position integer NOT NULL,
  seat_price numeric NOT NULL DEFAULT 0 CHECK (seat_price >= 0::numeric),
  status character varying NOT NULL DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'reserved'::character varying, 'booked'::character varying, 'blocked'::character varying]::text[])),
  booking_type character varying CHECK (booking_type IS NULL OR (booking_type::text = ANY (ARRAY['app'::character varying, 'phone'::character varying, 'agent'::character varying, 'walk_in'::character varying, 'blocked'::character varying]::text[]))),
  bus_booking_seat_id uuid,
  manual_booking_id uuid,
  block_reason text,
  blocked_by_user_id uuid,
  blocked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  held_by_intent_id uuid,
  held_until timestamp with time zone,
  CONSTRAINT trip_seats_pkey PRIMARY KEY (id),
  CONSTRAINT trip_seats_manual_booking_fkey FOREIGN KEY (manual_booking_id) REFERENCES public.manual_seat_bookings(id),
  CONSTRAINT trip_seats_trip_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT trip_seats_blocked_by_fkey FOREIGN KEY (blocked_by_user_id) REFERENCES public.users(id),
  CONSTRAINT trip_seats_bus_booking_seat_fkey FOREIGN KEY (bus_booking_seat_id) REFERENCES public.bus_booking_seats(id),
  CONSTRAINT fk_trip_seats_held_by_intent FOREIGN KEY (held_by_intent_id) REFERENCES public.booking_intents(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  device_id character varying NOT NULL,
  device_type USER-DEFINED NOT NULL,
  device_model character varying,
  app_version character varying,
  os_version character varying,
  fcm_token character varying,
  ip_address character varying,
  location_permission boolean DEFAULT false,
  notification_permission boolean DEFAULT false,
  last_activity_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  onesignal_player_id text,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone character varying NOT NULL UNIQUE,
  email character varying UNIQUE,
  first_name character varying,
  last_name character varying,
  nic character varying UNIQUE,
  date_of_birth date,
  address text,
  city character varying,
  postal_code character varying,
  roles ARRAY DEFAULT ARRAY['passenger'::text],
  profile_photo_url text,
  profile_completed boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'pending'::user_status,
  phone_verified boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  function_permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);